variable "OM_USECASE_LambdaTokenAuthorizer_InvokeARN" {}
variable "OM_USECASE_LambdaFunction_GET_FunctionName" {}
variable "OM_USECASE_LambdaFunction_GET_ARN" {}
variable "OM_USECASE_LambdaTokenAuthorizer_Name" {}
variable "OM_USECASE_LambdaTokenAuthorizer_Type" {}
variable "OM_USECASE_LambdaTokenAuthorizer_IdentitySource" {}
variable "OM_USECASE_APIGateway_Name" {}
variable "OM_USECASE_APIGateway_Description" {}
variable "OM_USECASE_APIGateway_EndpointType" {}
variable "OM_USECASE_APIGateway_Resource_PathPart" {}
variable "OM_USECASE_APIGateway_RequestValidator_Name" {}
variable "OM_USECASE_APIGateway_RequestValidator_ValidateRequestBody" {}
variable "OM_USECASE_APIGateway_HTTPMETHOD" {}
variable "OM_USECASE_APIGateway_Method_Authorization" {}
variable "OM_USECASE_APIGateway_Integration_TYPE" {}
variable "OM_USECASE_APIGateway_Integration_RequestTemplates" {}
variable "OM_USECASE_APIGateway_Integration_RequestParameters" {}
variable "OM_USECASE_APIGateway_IntegrationResponse_Post_ResponseTemplate" {}
variable "OM_USECASE_APIGateway_IntegrationResponse_PUT_ResponseTemplate" {}
variable "OM_USECASE_APIGateway_MethodResponse_DELETE_ResponseTemplate" {}
variable "OM_USECASE_APIGateway_MethodResponse_StatusCode" {}
variable "OM_USECASE_APIGateway_Method_PUT_HttpMethod" {}
variable "OM_USECASE_APIGateway_Method_DELETE_HttpMethod" {}
variable "OM_USECASE_APIGateway_Invoke_GET_StatementID" {}
variable "OM_USECASE_APIGateway_Invoke_GET_Action" {}
variable "OM_USECASE_APIGateway_Invoke_GET_Principle" {}
variable "OM_USECASE_Method_GET_HttpMethod" {}
variable "OM_USECASE_Integration_GET_Type" {}
variable "OM_USECASE_Integration_GET_ApplicationJson" {}
variable "OM_USECASE_MethodResponse_GET_ResponseModels" {}
variable "OM_USECASE_IntegrationResponse_GET_ResponseTemplate" {}
variable "OM_USECASE_APIGatewayDeployment_StageName" {}
variable "arn_apigateway" {}
variable "OM_USECASE_QueueSQS_path" {}
variable "aws_account" {}

variable "common_tags" {}
variable "iam_role_arn" {
  
}