variable "OM_USECASE_APIGateway_Execution_ARN" {}
variable "OM_USECASE_QueueSQS_Name" {}
variable "OM_USECASE_QueueSQS_DelaySeconds" {}
variable "OM_USECASE_QueueSQS_MaxMessageSize" {}
variable "OM_USECASE_QueueSQS_MessageRetentionSeconds" {}
variable "OM_USECASE_QueueSQS_VisisbilityTimeoutSeconds" {}
variable "OM_USECASE_QueueSQS_ReceiveWaitTimeSeconds" {}
variable "OM_USECASE_QueueSQS_ARN" {}
variable "common_tags" {}