variable "OM_USECASE_QueueSQS_ARN" {}

variable "OM_USECASE_QueueSQS" {}
variable "OM_USECASE_QueueSQS_URL" {}
variable "OM_USECASE_DynamoDBTable_Name" {}
variable "OM_USECASE_LambdaFunction_CRUD_FileName" {}
variable "OM_USECASE_LambdaFunction_CRUD_FunctionName" {}
variable "OM_USECASE_LambdaFunction_CRUD_Handler" {}
variable "OM_USECASE_LambdaFunction_Runtime" {}
variable "OM_USECASE_LambdaFunction_GET_FileName" {}
variable "OM_USECASE_LambdaFunction_GET_FunctionName" {}
variable "OM_USECASE_LambdaFunction_GET_Handler" {}
variable "OM_USECASE_LambdaTokenAuthorizer_FileName" {}
variable "OM_USECASE_LambdaTokenAuthorizer_FunctionName" {}
variable "OM_USECASE_LambdaTokenAuthorizer_Handler" {}
variable "OM_USECASE_LambdaTrigger_BatchSize" {}
variable "OM_USECASE_LambdaTrigger_MaximumBatchingWindowInSeconds" {}
variable "OM_USECASE_LambdaFunction_CRUD_FileName_archives" {}
variable "OM_USECASE_LambdaFunction_GET_FileName_archives" {}
variable "OM_USECASE_LambdaTokenAuthorizer_FileName_archives" {}
variable "OM_USECASE_LambdaFunction_CRUD_Archive" {}
variable "OM_USECASE_LambdaFunction_GET_Archive" {}
variable "OM_USECASE_LambdaTokenAuthorizer_Archive" {}
variable "common_tags" {}
variable "iam_role_arn" {}